server:
  name: "" # 服务名
  lark_notify_key: ""
  containers: # 监听的容器
    - "cross_chain_node-mysql-1"
  status: # 监听的状态
    - "start"
    - "stop"
supervisor: # supervisor events listening
  is_run: false
  lark_notify_key: ""